# Generated by Django 4.0.4 on 2022-05-12 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Oturucu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oturucu_teker', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Suretler_qutusu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suretler_qutusu', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Yanacaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yanacaq', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('marka_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.marka')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('distange', models.PositiveIntegerField()),
                ('engine', models.PositiveIntegerField()),
                ('choose', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('date_time', models.DateField(auto_now_add=True, null=True)),
                ('car_image', models.ImageField(upload_to='cars')),
                ('city', models.CharField(max_length=200)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.color')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marka_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.marka')),
                ('model_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.model')),
                ('oturucu_teker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.oturucu')),
                ('suretler_qutusu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.suretler_qutusu')),
                ('yanacaq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.yanacaq')),
            ],
        ),
    ]
